### ISSUE TITLE
After redirecting to another page the translations and default values don't appear on nav bar and footer component?

### ISSUE THREAD

**Issue by jhaji2911** [useflyyer/next-rosetta#18]

**Comment by lopezjurip** [comment]
Can you provide some example code?

- Make sure to export `getStaticProps` or `getServerSideProps` on each page and set the `table` prop.
- Did you add `<I18nProvider />` in your `_app` file?

**Comment by jhaji2911** [comment]
I did that and the translations are visible on all pages now  ,but how do I preserve the changed language on other page , I mean if I switch to some other page then  it resets to the default language back again.

**Comment by lopezjurip** [comment]
Can you show me how are you dealing with navigation?
Check our example: https://next-rosetta.vercel.app/ 
https://github.com/flayyer/next-rosetta/tree/main/example
