### ISSUE TITLE
Error in build process with Paths

### ISSUE THREAD

**Issue by sebastiansandoval27** [useflyyer/next-rosetta#37]
I'm executing "npm run build" but i have the next error: 

- This is the "getStaticProps" method.

![err1](https://user-images.githubusercontent.com/56927066/159746110-62238482-d533-4bae-bd66-5d707c77b68b.PNG)

- This is the error:

![err2](https://user-images.githubusercontent.com/56927066/159745409-5119c681-9ee2-460c-a125-b93d27e22f1c.PNG)
This error just appears when I export the "table" props of next-rosetta

**Comment by lopezjurip** [comment]
Make sure to have your `i18n` directory outside `/pages` 

Also check if the path at `await import(here)` is valid and it importing the expected file.
